name: Call Databus A10 Sheet Importer

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/databus-a10-sheet-importer.yml
    with:
      spreadsheet_url: "https://docs.google.com/spreadsheets/d/1d_dZAPjEsBGLGvskRVkunZU9pmWcHdMyGXoR3-9a2Z8/export?format=csv&gid=2032887030"
      artifact: "thecultch-events-sheet"
      publisher: "gregory"
