name: Call importer test

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/databus-a10-sheet-importer.yml
    with:
      spreadsheet_url: "https://docs.google.com/spreadsheets/d/1g_o9obh8h0e6sFKUl7C0LjADq5aqIWwgTDcSO4fYYK4/export?format=csv&gid=2032887030#gid=2032887030"
      artifact: "gregory-uat"
      publisher: "https://github.com/saumier#this"
