name: Databus A10 Sheet Importer

on:
  workflow_call:
    inputs:
      spreadsheet_url:
        description: 'Google Spreadsheet /export?exportFormat=csv'
        type: string
        required: true
      artifact:
        description: 'Artifact'
        type: string
        required: true
        default: 'test-events'
      publisher:
        description: 'Publisher ID'
        type: string
        required: true

jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-latest
    outputs:
      commit-hash: ${{ steps.get_commit_hash.outputs.commit-hash }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Main Script
        run: |
          mkdir -p artifacts
          bundle exec ruby main.rb \
            "${{ inputs.spreadsheet_url }}" \
            "${{ inputs.artifact }}" 
    
      - name: Commit and Push Changes
      
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add "artifacts/${{ inputs.artifact }}.json"
          git commit -m "Add data generated by the script"
          git push

      - name: Get commit hash
        id: get_commit_hash
        run: |
          commit_hash=$(git rev-parse HEAD)
          echo "commit-hash=$commit_hash" >> $GITHUB_OUTPUT           

  artsdata-push:
    runs-on: ubuntu-latest
    needs: fetch-and-commit-data
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v1.1.0
        with:
          artifact: ${{ inputs.artifact }}
          group: a10s-google-sheet
          publisher: "${{inputs.publisher}}"
          downloadUrl: https://raw.githubusercontent.com/artsdata-stewards/a10s-google-sheet-importer/${{ needs.fetch-and-commit-data.outputs.commit-hash }}/artifacts/${{ inputs.artifact }}.json

